title: "Shyam Sundar Debsarkar"
name: "Shyam Sundar Debsarkar"
description: "AI Research Scientist | PhD Candidate | Multimodal & Agentic AI for Biomedical Imaging"
url: "https://shyamTum.github.io"
baseurl: ""
email: "debsarss@mail.uc.edu"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

locale: "en-US"
markdown: kramdown
highlighter: rouge

# Site author (used by theme)
author:
  name: "Shyam Debsarkar"
  avatar: "/assets/img/headshot.jpg"
  bio: "PhD (ABD), Computer Science. AI Researcher in Multimodal AI, Medical Imaging, LLMs, VLMs, RAG, and Generative AI."
  location: "Cincinnati, OH, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:debsarss@mail.uc.edu"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=F7fDbbwAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/shyamTum"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/shyam-debsarkar/"

# Defaults: nice layout + readable width
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Header navigation
include:
  - _pages

# Optional: enable search (client-side)
search: true

# Optional: social preview
twitter:
  username: ""

# Exclude clutter
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-C8TH16Q79Y"
    anonymize_ip: false
